name: Deploy Docker App

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 👈 This enables the manual run button


jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Backend Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/testing-backend:latest ./backend

      - name: Push Backend Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/testing-backend:latest


      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/ashwin
            echo "env=${{ secrets.env }}" > .env
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/testing-backend:latest
            sudo docker-compose down
            sudo docker-compose -f docker-compose.yml up -d
